version: "3"
services:
  invoiceee-app:
    container_name: invoiceee-app
    image: php:8.0
    ports:
      - 8000:8000
    volumes:
      - .:/opt/invoiceee
    command:
      - "bash"
      - "-c"
      - "cd /opt/invoiceee && php artisan serve --host 0.0.0.0"
  invoiceee-db:
    container_name: invoiceee-db
    image: mysql:8
    environment:
      MYSQL_DATABASE: invoiceee
      MYSQL_USER: invoiceee
      MYSQL_PASSWORD: invoiceee
      MYSQL_ROOT_PASSWORD: invoiceee
    ports:
      - "3306:3306"
    volumes:
      - invoiceee-db:/var/lib/mysql
volumes:
  invoiceee-db:
    driver: local
